---

- hosts: all
  become: true
  tasks:
  
  - name: install the apache2  and php package and update cache
    package:
      name: 
        - "{{ apache_package}}"
        - "{{php_package}}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: my_vms
  become: true
  tasks:
  
  - name: install python
    package:
      name: python3
      state: present
      
  - name: verify python installation
    command: python3 --version
    register: python_version
  
  - name: display python version
    debug:
       msg: "Python version installed: {{ python_version.stdout }}"       
            

  - name: start httpd service (CentOS)
    tags: centos,httpd,apache
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"            
