---

- hosts: all
  become: true
  tasks:
  
  - name: install the apache2  and php package and update cache
    package:
      name: 
        - "{{ apache_package}}"
        - "{{php_package}}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
      
            
